### PR TITLE
Create View classes

### LINKED ISSUE #30: Refactor input dependent methods
Probably change update/spawn/interact methods to not take a string directly, instead add .use method. This would allow us to send multiple inputs in (e.g. from an async JavaFX handler) before updating, as well as seperate the update methods from the actual input, which can vary between text/graphic.

### LINKED ISSUE #32: Implement graphical display and input.
Likely create a View class that takes a Canvas (JavaFX) and Room, and blits the Room's Displayables onto the Canvas (probably after clearing the canvas). Also link the View to a Controller (maybe a new GraphicController) and figure a way to collect key events and pass them to the Room. (This issue will probably be done after the command string refactor).

### PR DESCRIPTION
**Pull request by rupertraphael**
My goal was to have us separate the logic for displaying a room from all of the other things that a room does. So, I've created an abstract View class which can be extended by other view classes. 

Currently, a View requires a `model` and displays the model to the user depending on how its `render` function is implemented. Ideally, a view should be initialized in a controller, and its `render` function called from there.

For example, the `TextView`, displays the grid which @jaewon-ma implemented. On the other hand, `GameView`, requires a `Graphics2DContext` (still playing around as to which object GameView should require) from JavaFx in order to draw the model into the canvas. And for now, it displays a JavaFx version of Jacob's grid.

I did make some changes to `Main` in order to implement JavaFx into the app. And I removed the functionality to control the room entities. For now, it just renders the room.

This pull request is more of a proposal rather than something that should be merged. I just want to know if this design pattern has the potential to be included in our project.

### CODE REVIEW

**Comment by HN67** [comment]
I'll take a closer look this evening when I have time, but I think I like the View architecture. We could probably pass a stream to the textview instead directly using system.out. Ideally I would like to have a thin Main class still and somehow create a FX application, but I don't know if it is possible. Maybe we can make a controller extend Application.

**Comment by rupertraphael** [comment]
@HN67, I've drafted the part for handling keypresses and moving the rectangles around the canvas injected into RoomView. On every keypress, the controller `handle` function is called. It does the following: 

1. interprets key presses into movements for the room, 
2. adds them to the command queue,
3. updates the room,
4. renders the views, and;
5. clears the queue

I'm not quite sure if I properly used the command queue functionality that you just introduced.

Also, I temporarily commented out the part where commands are queued for spawners in TextRoom. This duplicated the commands for Player and Bullets which had a really weird side-effect.

**Comment by HN67** [comment]
Yeah i actually had implemented something almost identical for handling key presses, but I didn't think of the spawner/entity duplication in Player. Might change the command queues to be sets to prevent duplication, but then we lose order of events (dont know if that matters). I would like to move the updating and rendering into a game loop (60 FPS) using AnimationTimer or Timeline. I think Timeline is more flexible but I couldnt get it working last night.

**Comment by HN67** [comment]
I have pretty much full control implemented. Movement is a little janky though because if we rely on the event every tick, JavaFX wont send it every tick, so to make it smoother I just dont reset. Maybe we can improve the handle method and/or update method to add a movement command to the queue on key press and remove it on key release, not remove automatically.

**Comment by HN67** [comment]
Relatively happy with the event handling now, and the graphical display. It gets a little laggy when a ton of entities spawn, but I don't think we will ever have nearly that many entities in a real game, so I dont think it is really an issue right now. I think we are good to merge.

**Pull request merged**
