### PR TITLE
Initial Implementation for Item

### LINKED ISSUE #3: Create Item Interface
An Item should represent a conceptual in-game object, such as a Consumable (Food, etc) or Weapon. Another interpretation is that an Item is something that can exist inside an Inventory. The core functionality of an Item needs to be able to determine whether it is equal to another Item (i.e. through a .equals(Item) method), likely by comparing a name or ID. An Item may also expose attributes such as name and ID (which would be intended to be unique in the game, and may be a simpler data type than the name). More functionality of an Item will likely either be delegated to implementations or added when the game design is more developed (e.g. sell price).

### PR DESCRIPTION
**Pull request by rupertraphael**
I've created an abstract Item class which contains three methods. `.equals()`, `.name()`, and `.description()`.

The first one is a concrete implementation .equals(). It simply checks if both items (the current item object and another item object) belong to the same concrete class. For example, I've created concrete item classes Caffeine and HalfAndHalf. If you instantiate a Caffeine object called caffeine and a HalfAndHalf object called halfAndHalf and writes caffeine.equals(halfAndHalf), you should get false, and vice-versa. Otherwise, if both of them were from the same kind of class. Say, both of them were Caffeine objects or HalfAndHalf objects, you'd get true. I've implemented .equals() for Item this way because from what I can see, we just need to check if both items would be the same kind (specifically, class) when we aggregate them inside an Inventory.

Although, I might be wrong and there might be a use case where we might need to check if each instance of an item is different from another. If we do, I will create a new method to save the above functionality and rewrite .equals().

Anyway, the remaining two classes are abstract. Concrete item classes must override it and return their respective names and descriptions. Checkout the sample concrete item classes that I've implemented.

Btw, my reason for creating an abstract class as opposed to an interface is just the fact that I just have 3 methods in it and it would be easier to track all of them inside on abstract class. If more methods get written, we might extract them into interfaces that maybe shared across all of our other classes.

### CODE REVIEW

**Comment by rupertraphael** [comment]
Would love to learn how to use JUnit, though, and create tests for these. I'll see when I have more extra time during the weekend.

**Comment by HN67** [comment]
I like this implementation, especially the equals method. I think abstract class is fine, the only disadvantage is it doesn't work as well with multiple inheritance, which probably wont be an issue. I'm fine with merging as is.

**Comment by rupertraphael** [comment]
Ok, I might hold off on merging for now. I might have some time to practice writing tests for these over the week.

**Comment by rupertraphael** [comment]
I change my mind, I'm just gonna push to prevent potential merge conflicts when the other guys submit pull requests.

**Pull request merged**
